name: Node.js CI

on:
  push:
    branches:
      - master    # Trigger this workflow on push to main
  pull_request:
    branches:
      - master    # Trigger for pull requests targeting main

jobs:
  # Frontend Build & Tests
  Build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (Frontend)
      uses: actions/setup-node@v2
      with:
        node-version: '20.18.0'  # Change this to your required Node.js version

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        set -x
        npm i

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: CI=false npm run build  # build the react applications

    - name: Install Backend Dependencies
      working-directory: ./backend  # Change to the backend folder
      run: npm i


    - name: Ensure nodemon is executable
      run: chmod +x ./backend/node_modules/.bin/nodemon # change the nodemon permissions if not included a permission denied error may arise